# Generated by Django 3.2.9 on 2021-11-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('workout1', models.TimeField()),
                ('workout2', models.TimeField()),
                ('workout3', models.TimeField()),
                ('workout4', models.TimeField()),
                ('workoutTotal', models.TimeField()),
            ],
        ),
    ]
