# Generated by Django 3.2.9 on 2021-11-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttimes',
            name='user',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='workouttimes',
            name='workoutTotal',
            field=models.DateTimeField(),
        ),
    ]
