# Generated by Django 3.2.9 on 2021-11-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_auto_20211112_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttimes',
            name='workout1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workouttimes',
            name='workout2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workouttimes',
            name='workout3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workouttimes',
            name='workout4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workouttimes',
            name='workoutTotal',
            field=models.FloatField(),
        ),
    ]
