# Generated by Django 3.2.9 on 2021-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_auto_20211112_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttimes',
            name='workoutTotal',
            field=models.IntegerField(),
        ),
    ]
