# Generated by Django 3.2.9 on 2021-11-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_alter_workouttimes_workouttotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttimes',
            old_name='workoutTotal',
            new_name='points',
        ),
    ]
